### ISSUE TITLE
Authentification sur serveur distant (pour stocker les backups)

### ISSUE THREAD

**Issue by gaudouy** [blogmotion/bm-backup-pfsense#1]
Hello, 

Merci pour ton script ! C'est top !

Est-il possible d'intégrer dans ton script un moyen de saisir les identifiants d'un lecteur réseau distant afin d'y stocker les backups ?

Merci d'avance.

Cordialement
Gaudouy

**Comment by blogmotion** [comment]
Hello,

Je t'invite à utiliser **autofs** pour gérer ton point de montage indépendamment du script, ensuite utilise ta destination montée comme chemin dans le script.

Bonne journée!
