### ISSUE TITLE
Gestion des erreurs en version multi

### ISSUE THREAD

**Issue by peng42** [blogmotion/bm-backup-pfsense#2]
Bonjour,

Merci pour ces scripts, très utiles.

Une petite remarque concernant la version multi : si un des backups échoue (machine injoignable...), le script lève l'erreur et ne tente pas de sauvegarder les machines suivantes dans la liste.

Pour reproduire : avec trois pfsense configurés, je désactive l'utilisateur backup sur la machine 2.
Comportement actuel : backup OK sur machine 1, erreur sur machine 2.
Comportement attendu : backup OK sur machines 1 et 3, erreur sur machine 2.

Bonne journée,

Fabien

**Comment by blogmotion** [comment]
Bonjour @fsirjean, merci c'est corrigé, peux-tu tester et me faire un retour ?
