### ISSUE TITLE
Improvement : unused variable BACKUP_NAME

### ISSUE THREAD

**Issue by dcpc007** [blogmotion/bm-backup-pfsense#3]
https://github.com/blogmotion/bm-backup-pfsense/blob/e53e26b91f026d7973128ccf8b065e325212c586/pfmotion_curl.sh#L35

Hi, this variable isn't use in the script. The line could be removed in scripts

**Comment by blogmotion** [comment]
fixed : the variable was present because of the simple version (an oversight) thank you
