### ISSUE TITLE
Improvement : new variables

### ISSUE THREAD

**Issue by BenPi-Ross** [blogmotion/bm-backup-pfsense#5]
Hello!

I've created a patch for the curent version of "pfmotion_curl.sh" (2024.02.29_cURL) to suggest some improvements.
[pfmotion_curl.sh.patch](https://github.com/blogmotion/bm-backup-pfsense/files/14530778/pfmotion_curl.sh.patch)

This patch contains these modifications : 
1. Adds the following two backup parameters as variables :
- &backupdata=yes
- &backupssh=yes
2. It also adds a variable to toggle the "--insecure" parameter of curl.

Feel free to improve on it.

Thanks!

**Comment by blogmotion** [comment]
Hello @BenPi-Ross, thank you for this report. 
I've made a few improvements and incorporated the suggestions. Come back to me in case of problems

**Comment by blogmotion** [comment]
Fixed in [dad7031](https://github.com/blogmotion/bm-backup-pfsense/commit/dad7031ab727184df4d85653e455084461f66343)

**Comment by BenPi-Ross** [comment]
I've tested your new version of the script and there's a bug with the HTTPS_INSECURE variable, more specifically it's associated CERT variable.

Since you put double quotes around the variable ("$CERT") in the last three curl commands, curl thinks that it's a second URL parameter and gives the following error for that empty string/URL :
`curl: (3) URL rejected: Malformed input to a URL function`

I've removed the double quotes around it, so if the variable HTTPS_INSECURE is set to 0 and that the CERT variable stays unset (null), the curl command works without error this time.

For exemple :
`# fetch login
curl -Ss --noproxy '*' $CERT --cookie-jar "$COOKIE_FILE" "$PFSENSE_HOST/diag_backup.php" \
  | grep "name='__csrf_magic'" | sed 's/.*value="\(.*\)".*/\1/' > "$CSRF1_TOKEN" \
  || echo "ERROR: FETCH"`
instead of :
`# fetch login
curl -Ss --noproxy '*' "$CERT" --cookie-jar "$COOKIE_FILE" "$PFSENSE_HOST/diag_backup.php" \
  | grep "name='__csrf_magic'" | sed 's/.*value="\(.*\)".*/\1/' > "$CSRF1_TOKEN" \
  || echo "ERROR: FETCH"`

I don't know if there's another way around this but it works in my tests without the double quotes.

**Comment by blogmotion** [comment]
> I've tested your new version of the script and there's a bug with the HTTPS_INSECURE variable, more specifically it's associated CERT variable.
> 
> Since you put double quotes around the variable ("$CERT") in the last three curl commands, curl thinks that it's a second URL parameter and gives the following error for that empty string/URL : `curl: (3) URL rejected: Malformed input to a URL function`
> 
> I've removed the double quotes around it, so if the variable HTTPS_INSECURE is set to 0 and that the CERT variable stays unset (null), the curl command works without error this time.
> 
> For exemple : `# fetch login curl -Ss --noproxy '*' $CERT --cookie-jar "$COOKIE_FILE" "$PFSENSE_HOST/diag_backup.php" \ | grep "name='__csrf_magic'" | sed 's/.*value="\(.*\)".*/\1/' > "$CSRF1_TOKEN" \ || echo "ERROR: FETCH"` instead of : `# fetch login curl -Ss --noproxy '*' "$CERT" --cookie-jar "$COOKIE_FILE" "$PFSENSE_HOST/diag_backup.php" \ | grep "name='__csrf_magic'" | sed 's/.*value="\(.*\)".*/\1/' > "$CSRF1_TOKEN" \ || echo "ERROR: FETCH"`
> 
> I don't know if there's another way around this but it works in my tests without the double quotes.

Thank you, I fixed this (double quoted removed)
Check https://github.com/blogmotion/bm-backup-pfsense/commit/bd3b2f8811881c91e450477073a878a5f1bece5c
